### ISSUE TITLE
Wildcard and SANS

### ISSUE THREAD

**Issue by yctn** [mprahl/ansible-role-lets-encrypt-route-53#19]
"msg": "Error requesting challenges: CODE: 400 RESULT: {u'status': 400, u'type': u'urn:acme:error:malformed', u'detail': u'Error creating new authz :: Wildcard names not supported'}",

seems like this implementation does not support wildcard records?

Also when you would use 2 subdomains things break.
in my csr is can see do domains with 2 subdomains but they are not in the resulting cert.
with 2 subdomain i mean sub1.sub2.mydomain.com

**Comment by fishhead108** [comment]
The same here

**Comment by mprahl** [comment]
#24 should fix this.
