### ISSUE TITLE
Question: Renewal of certificates

### ISSUE THREAD

**Issue by anlx-sw** [mprahl/ansible-role-lets-encrypt-route-53#23]
Hi, I just try to read through the code and documentation - and I can't find anything really concerning renewal.

Is the role required to be re-applied <10 days before the certificate expires for renewal or are the renewals done by some process configured on the target system?

Thanks!

**Comment by mprahl** [comment]
Hello,
The renewals are handled by running the role again when the cert is 10 days or less from expiring.

Please let me know if you have any other questions.
