### ISSUE TITLE
feature request Renewal on target

### ISSUE THREAD

**Issue by dumarjo** [mprahl/ansible-role-lets-encrypt-route-53#28]
hi,

First, thank you for your effort !!

I would like to know if it's possible to add the possibility to have the target renew the certificate itself from the dns01 challenge?

Regards

Jonathan

**Comment by mprahl** [comment]
Hi @dumarjo,
The target will not renew the certificate on its own.

The way I have it set up is I run an Ansible playbook that uses this role through Ansible Tower once per week. You could use a cronjob if you don't have Ansible Tower. If the current certificate has `ler53_cert_remaining_days_before_renewal` (defaults to 10) days or less, the role will automatically renew the certificate.

I hope this helps!
