### ISSUE TITLE
Add official support for RHEL 8

### ISSUE THREAD

**Issue by mprahl** [mprahl/ansible-role-lets-encrypt-route-53#30]
This role assumes that RHEL 7 is used and creates a virtualenv and installs the dependencies via pip since the packaged Python dependencies are not recent enough. This may not be necessary for RHEL 8.

**Comment by oldirtybasti** [comment]
When I execute a playbook on AWX i get the following error:

TASK [mprahl.lets-encrypt-route-53 : install the required dependencies (Red Hat) (Requires EPEL)] ***
fatal: [10.0.0.4]: FAILED! => {"changed": false, "failures": ["No package python-pip available."], "msg": "Failed to install some of the specified packages", "rc": 1, "results": []}

Is that bug associated with your issue?

**Comment by mprahl** [comment]
#38 should address this.
