### ISSUE TITLE
Subject fields redundant

### ISSUE THREAD

**Issue by stevenringo** [mprahl/ansible-role-lets-encrypt-route-53#4]
```
ler53_cert_subject: "/C={{ ler53_cert_country }}/ST={{ ler53_cert_state }}/L={{ ler53_cert_locality }}/O={{ ler53_cert_organization }}/CN={{ ler53_cert_common_name }}"
```

Except for the CN, all these fields are removed by LE, as these are DV and not OV validated. They don't want to be putting in the names, addresses, etc. of an organisation that they have not validated.

Therefore, you might as well remove them 😄 ...

**Comment by mprahl** [comment]
Thanks for the tip! I removed these variables in commit [77d2b2532e929184e29fc88af8ea12cf44a55ee5](https://github.com/mprahl/ansible-role-lets-encrypt-route-53/commit/77d2b2532e929184e29fc88af8ea12cf44a55ee5)
