### ISSUE TITLE
Consistency check of private key is failing

### ISSUE THREAD

**Issue by gnunn1** [mprahl/ansible-role-lets-encrypt-route-53#51]
I've been using this role for awhile now (great job BTW) however in the last 6 months I've started running into an issue where the cosnistency check assertion for the private key at the end of the play fails. This seems to be due to this problem earlier in the play, is there something I'm missing in the config to workaround this?

I'm on Arch Linux so latest and greatest of everything  with ansible 2.17 and openssl 3.3

```
TASK [mprahl.lets-encrypt-route-53 : check consistency of private key] *******************************************************************************************************************************************************************************************************************
[WARNING]: Cannot determine consistency for key of type <class 'cryptography.hazmat.bindings._rust.openssl.rsa.RSAPrivateKey'>
```

**Comment by mprahl** [comment]
I started getting other errors on FreeBSD related to the Python cryptography module. I decided to remove the consistency checks in #53. I hope this helps!
