### ISSUE TITLE
New letsencrypt intermediates (R10, R11) issues

### ISSUE THREAD

**Issue by gnunn1** [mprahl/ansible-role-lets-encrypt-route-53#54]
LetsEncrypt has rolled out some new intermediates and will cycle between them (i.e R10 versus R11) but the playbook is coded to download R3 by default. Changing this is easy enough but AFAIK letsencrypt does not guarentee which intermediate you end up with (R10 or R11) so does the playbook need to be a little more sophisticated in figuring out the intermediate to download?

Also I'm not familiar with the guts of this playbook and the underlying tooling, but using acme.sh I believe letsencrypt provides the actual intermediate in fullchain.pem, why download it again?

**Comment by gnunn1** [comment]
Yeah, this is broken unfortunately. I uploaded the download variable to use R10, re-ran the play and then promptly got an R11 certificate.

**Comment by prabumohan** [comment]
how did you fix this . I use R10 and I get get error while doing a curl

**Comment by mprahl** [comment]
@prabumohan I think the solution is rather than build the certificate chain in the Ansible role, we can leverage the `fullchain_dest` parameter from `acme_certificate`. I'll try this out when I get a chance but if anyone wants to try this out and contribute a PR, I'd gladly review the PR.

**Comment by prabumohan** [comment]
Anyone had any luck?  i couldn't get it working

**Comment by mprahl** [comment]
This is now fixed in v6.0.0!
