### ISSUE TITLE
Certificates are not renewed when the domains are updated

### ISSUE THREAD

**Issue by AndreaGiardini** [mprahl/ansible-role-lets-encrypt-route-53#7]
Hi

I tried your module and I figured out that whenever i change the list of domains in the `ler53_cert_sans` variable a new certificate is not generated. Am I missing something or it hasn't been implemented yet? Any tip on how to do it?

Thank you for the great work :+1:

**Comment by mprahl** [comment]
@AndreaGiardini I believe it is from this line:
https://github.com/mprahl/ansible-role-lets-encrypt-route-53/blob/master/tasks/main.yml#L69

It currently checks to see if the CSR exists, if it does, then it skips creating it. Later on I can try to add logic to check the domain names.

**Comment by mprahl** [comment]
@AndreaGiardini this commit should address your feature request:
https://github.com/mprahl/ansible-role-lets-encrypt-route-53/commit/83e210f31aa1d1ad437ad36f34ee9e82f828f375

In that commit, I added a variable called `ler53_new_cert_when_csr_changes`. If you set that to `true`, Ansible will delete the certificate if the CSR changes, and then the Let's Encrypt request will go through as a new certificate request.

Sorry about the delay on this, it just took some other refactoring as well.
